### ISSUE TITLE
HOw to use?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [niobos/vobsubfix#1]
It outputted something 
`timestamp: 00:53:45:584, filepos: 00243800: SPU length 686
timestamp: 00:53:47:542, filepos: 00244000: SPU length 2404
timestamp: 00:53:51:959, filepos: 00245000: SPU length 1958`

But the file itself remained unchanged.

I did ./vobsubfix.py file.idx

The results is above

I tried running vobsub.py but i keep getting errors

How do i exactly install and run/use this?

**Comment by niobos** [comment]
Hi OilSubjectLoss7,

This looks like the expected behaviour: This code will replace 0-length SPUs with padding. Based on the output, there are no 0-length SPUs, and thus nothing is replaced, leaving the file unchanged.
