### ISSUE TITLE
Can't locate Data/ParseBinary.pm in @INC (you may need to install the Data::ParseBinary module)

### ISSUE THREAD

**Issue by OilSubjectLoss7** [niobos/vobsubfix#2]
I'm getting this err message when i try
`./vobsub.pl`
`/vobsubfix.pl` is more responsive but i don't think it's doing anything.

**Comment by niobos** [comment]
Can you elaborate on what you already tried to resolve this error?
The message says to make sure you installed Data::ParseBinary, did you verify that?

**Comment by OilSubjectLoss7** [comment]
Thanks, it's working now. you should probably put this in a requeriment or something

https://github.com/shmuelfomberg/perl-cpan-data-parsebinary
