### ISSUE TITLE
I speak too soon

### ISSUE THREAD

**Issue by OilSubjectLoss7** [niobos/vobsubfix#3]
Global symbol "$parser" requires explicit package name (did you forget to declare "my $parser"?) at /usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary/Core.pm line 
Global symbol "$parser" requires explicit package name (did you forget to declare "my $parser"?) at /usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary/Core.pm line 
Compilation failed in require at /usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary.pm line 8.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary.pm line 
Compilation failed in require at /home/.autojump/bin/vobs line 
BEGIN failed--compilation aborted at /home/.autojump/bin/vobs line 7.

How to fix this?

**Comment by OilSubjectLoss7** [comment]
Nevermind, i fixed with
`
cpan -if Data:ParseBinary
`

**Comment by OilSubjectLoss7** [comment]
Oops.

Is this supposed to happen or is this another roadblock?

Got Exception @0x3 Expected PES sync, but got: 23 20 56

Streams location:
1: Stream DS::PES in byte #0
Constructs Stack:
1: Primitive length
 at /usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary/Core.pm line 45.
         Data::ParseBinary::BaseConstruct::parse(Data::ParseBinary::Primitive=HASH(0x7687873a38), DS::PES=HASH(0x7687871828)) called at /home/.autojump/bin/vobs line 191

**Comment by niobos** [comment]
That error indicates that the provided file is not a Packetised Elementary Stream. What type of file are you trying to process? Are you sure this is a .idx/.sub pair extracted from a DVD?

**Comment by OilSubjectLoss7** [comment]
It's made from a program not extracted from a dvd


Edit:

I tried it on a geniune dvd idx and i got the same error

**Comment by niobos** [comment]
Can you provide detailed steps to reproduce? What command are you running? Can you provide the file(s) you are running this command on?

**Comment by OilSubjectLoss7** [comment]
> Can you provide detailed steps to reproduce? What command are you running? Can you provide the file(s) you are running this command on?

vobsub.pl 𝗳𝗶𝗹𝗲
[sample.zip](https://github.com/niobos/vobsubfix/files/8167827/sample.zip)

**Comment by niobos** [comment]
Can not reproduce.
Here I get the expected behaviour:
```
$ ./vobsubfix.pl sample.idx
timestamp: 00:00:03:417, filepos: 00000000: SPU length 2237
timestamp: 00:00:04:959, filepos: 00001000: SPU length 2640
timestamp: 00:00:08:583, filepos: 00002000: SPU length 539
timestamp: 00:00:10:041, filepos: 00002800: SPU length 1430
[...]
```

**Comment by OilSubjectLoss7** [comment]
Here's what i get if i run the second file **vobsubfix.pl**

> vobsubfix.pl sample_02.idx                   
timestamp: 00:00:03:375, filepos: 00000000: SPU length 1421       
timestamp: 00:00:04:917, filepos: 00000800: SPU length 2560       
timestamp: 00:00:08:542, filepos: 00001800: SPU length 349

The main file itself **vobsub.pl**

vobsub.pl sample_02.idx
Got Exception @0x3 Expected PES sync, but got: 23 20 56

Streams location:
1: Stream DS::PES in byte #0                                      Constructs Stack:                                                 1: Primitive length
 at /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.0/Data/ParseBinary/Core.pm line 45.
        Data::ParseBinary::BaseConstruct::parse(Data::ParseBinary::Primitive=HASH(0x7e64b95318), DS::PES=HASH(0x7e64bc1e40)) called

[Sample_02.zip](https://github.com/niobos/vobsubfix/files/8167966/Sample_02.zip)

**Comment by niobos** [comment]
What are you actually trying to accomplish?

`vobsub.pl` is a simple parser/dumper for the `.sub` files, so you should run it on the `.sub`, not the `.idx`

**Comment by OilSubjectLoss7** [comment]
Oh, how do i use it exactly?

Apply them for each ext(idx,sub)?

So for sub files use the vobsub.pl
And for the idx use the vobsubfix.pl?
Is that right?
